### ISSUE TITLE
Add ability to add title to viz.draw

### ISSUE THREAD

**Issue by robertness** [py-why/pywhy-graphs#23]
**Is your feature request related to a problem? Please describe.**
I want to visualize several graphs and distinguish them with a title.

**Describe the solution you'd like**
An optional argument for an image title.

**Describe alternatives you've considered**
Adding title outside of image.  A bit clumsy.

**Additional context**
I'm trying to compare graphs.

**Comment by adam2392** [comment]
One can add a keyword argument to `draw()` inside `pywhy-graphs/viz`

**Comment by aryan26roy** [comment]
Hi @robertness , @adam2392. I am looking to contribute to the library and this looks like a good first issue. Do you mind if I take this?

**Comment by adam2392** [comment]
Sure!
