### ISSUE TITLE
Add support for undirected edges in m-separation

### ISSUE THREAD

**Issue by jaron-lee** [py-why/pywhy-graphs#43]
**Is your feature request related to a problem? Please describe.**
Currently the m-separation function in `pywhy_graphs/networkx/algorithms/causal/m_separation.py` only supports directed and bidirected edges. 

**Describe the solution you'd like**
Extend the m-separation function to incorporate logic over undirected edges.

**Describe alternatives you've considered**
Could implement this in a separate function, but I anticipate the implementation will leverage machinery that exists already in the m-separation function.

**Additional context**
This function would be useful because currently `dodiscover/ci/oracle.py` has an Oracle class that accepts any graph (including a PAG) but does not support dealing with undirected edges, since it uses. This allows a user to create a CI Oracle that does not detect dependence where undirected edges are involved, hampering downstream tasks like e.g. verifying FCI works correctly under selection bias.

**Comment by adam2392** [comment]
Clarifying that this proposal is to support ADMGs with directed, bidirected and undirected edges right? +1.

To enable it to work w/ undirected edges, I guess a naive approach would be to add a dummy collider node that is always conditioned on? So one might need to keep track of the added dummy collider nodes. But maybe there's a better way using the existing machinery inside the m-separation function.

Re PAGS: I think for doing "m-separation" on PAGs, we'll need a new function (i.e. `definite_m_separated` or something like `possibly_m_separated`), so we can tackle that in another issue.

**Comment by jaron-lee** [comment]
I think that's right, although strictly speaking that would not be an ADMG anymore (due to the undirected edges). 

I misspoke earlier - the use case I had in mind was creating a conditional independence oracle from a MAG, and then running FCI over that oracle to see what kind of graph would be recovered. I notice that there is not a separate class yet for MAGs (although DAGs has CPDAGs so I imagine this is in the pipeline or is already an issue that I hadn't noticed). In any case we would not need to consider definite vs possibly yet.

**Comment by adam2392** [comment]
Yeah MAGs hasn't been implemented because normally one would not have access to the MAG, but should be fairly straightforward given the other graph classes, if you think it's important.

**Comment by adam2392** [comment]
I'm +1 for adding undirected edge support into `m_separated` function. If you need the MAG class to make this work then, we can start there.

**Comment by jaron-lee** [comment]
I don't think I immediately need to set up a MAG class to make this work - I believe I can probably use the PAG without circle edges for the purposes of developing this function.
