### ISSUE TITLE
M-separation does not work

### ISSUE THREAD

**Issue by jaron-lee** [py-why/pywhy-graphs#47]
## Checklist

- [ ] I have verified that the issue exists against the `main` branch.
- [ ] I have read the relevant section in the [contribution guide](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/py-why/pywhy-graphs/issues) for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/py-why/pywhy-graphs/pulls) for existing proposed fixes.
- [ ] I have checked the [CHANGELOG](https://github.com/py-why/pywhy-graphs/blob/main/CHANGELOG.md) and the [commit log](https://github.com/py-why/pywhy-graphs/commits/main) to find out if the bug was already fixed in the main branch.
- [ ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

I encountered a test case where the m-separation implementation fails, and the way it fails leads me to think that the approach of extension of the d-separation algorithm from Darwiche 2007 (e.g. the networkx implementation) does not work, and I don't have confidence that this extension is sound without further detailed investigation.

In particular, consider the graph A -> B, B -> D, B <-> C. Currently the m-separation implementation fails to detect A independent of C marginally. I attempted to devise a fix, but encountered further problems in dealing with undirected edges.

I found https://arxiv.org/pdf/1803.00116.pdf which provides a linear time m-separation criterion for ancestral graphs. I propose to implement that instead.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by adam2392** [comment]
Ah I have seen that paper before and it is interesting to me. Yeah let's implement that if you're up for it. I verify that the unit test fails... Will be good to include this in the unit-tests for the next implementation.

```Python
   d_G = nx.DiGraph()
    b_G = nx.Graph()
    G = pywhy_nx.MixedEdgeGraph([d_G, b_G], edge_types=['directed', 'bidirected'])

    G.add_edge('A', 'B', edge_type='directed')
    G.add_edge('B', 'D', edge_type='directed')
    G.add_edge('A', 'C', edge_type='bidirected')
    assert pywhy_nx.m_separated(G, {'A'}, {'C'}, {})

```
Alas the problem of developing graph-algorithms. The unit tests are merely loose tests of necessity, not sufficiency.

It seems that paper also contains methods to "enumerate" (minimal) m-separators in polynomial-delay time(?) That could also be useful for the future.

**Comment by jaron-lee** [comment]
I only mention this failing test as an example, but I have in a fork a whole pile of failing tests which I will add to the eventual PR. I spent a while messing with extending Darwiche algorithm but we probably want something more theoretically secure.

**Comment by adam2392** [comment]
Yeah I agree. Lmk if you need help with this beyond reviewing code.
