### ISSUE TITLE
Conversion API to other causal libraries' graph

### ISSUE THREAD

**Issue by adam2392** [py-why/pywhy-graphs#57]
**Is your feature request related to a problem? Please describe.**
We should expose an API (there is one untested really rn) for exporting to the following packages:

- tigramite (3D time-series graph that supports time-series DAG, ADMG, PAG) -> WIP
- pgmpy (DAG and PDAG)
- causal-learn (currently we have this implemented) -> done
- dagitty (DAG, ADMG) -> handled by pygraphviz
- pcalg -> done
- networkx to a DiGraph with a specific structure
- numpy (tigramite, causal-learn, pcalg are all numpy-like array structures) -> done
- ananke -> @jaron-lee to handle
- tetrad text -> done
- bnlearn -> handled by pygraphviz I think

This will enable pywhy-graphs to be interoperable across many other packages and also allow other users to take their graphs and convert to pywhy-graphs for the sake of using it in `dodiscover` and `dowhy`.

**Describe the solution you'd like**
If the other package is not in R, we can directly test roundtrip compatibility.

If the other package is in R, we should just do some basic testing that the format is "as expected". I think loading in R runtime is a whole other beast we don't want to figure out how to do in the CI pipeline.

The solution requires the following for each export:

io roundtrip: That is the basic graph structure should be preserved. Some metadata might be lost depending on the format each package stores graphs in. When possible, metadata should be preserved. A unit test would look like the following where the edge and node structure is preserved.

```Python
pcalg_G = pywhy_graphs.export(G, 'pcalg')
G_copy = pywhy_graphs.import(G, 'pcalg')

for edge_type in G.edge_types:
    assert nx.is_isomorphic(G.get_graphs(edge_type), G_copy.get_graphs(edge_type))
```

**Additional context**
n/a

**Comment by jaron-lee** [comment]
I would also be happy to extend the API to ananke!

**Comment by adam2392** [comment]
I think based on today's discussion, this seems pretty high value. So I'ma start chipping away at this. Happy to review PR related to ananke. 

Re all these packages btw, we'll only add them as soft dependencies for unit-testing purposes. This will go into the poetry group `test` in the `pyproject.toml` file

**Comment by jaron-lee** [comment]
Will get started on this later this week, on the ananke side I need to remove a hard dependency on `graphviz` and make sure that didn't break anything.

**Comment by adam2392** [comment]
> Is there a rough sketch of how the api should look? Presumably we want to expose a set of functions that all look and behave roughly the same. One idea that comes to mind is the pandas export functionality, where `df.to_<format>()` is the pattern.

Currently, I have a functional API, which is just `graph_to_<format>` and `<format>_to_graph`. We can add more convenience once we have the working functions.


> Will get started on this later this week, on the ananke side I need to remove a hard dependency on `graphviz` and make sure that didn't break anything.

You can keep it if you want, and just make `ananke` an optional dependency.

**Comment by adam2392** [comment]
Everything is done that is doable except Ananke now.

Note: some of the other packages which only supports DAGs, I did not handle or implement. I think those work fine w/ nx.DiGraph for now, so community can PR that if they want it.

**Comment by adam2392** [comment]
Example about tetrad conversion and other library conversion in examples script.
